services:
  - type: web
    name: gameframe
    env: node
    rootDir: GameFrameJS
    region: ohio
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg
      npm install
    startCommand: npm start
